/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.4).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Tenants;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-03-28T18:55:48.493Z")

@Api(value = "tenants", description = "the tenants API")
public interface TenantsApi {

    @ApiOperation(value = "Get info about tenants", nickname = "getTenants", notes = "Returns a list of tenants", response = Tenants.class, tags={ "tenant", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Tenants.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Tenant not found") })
    @RequestMapping(value = "/tenants",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Tenants> getTenants();

}
